---
title: "Subjects count"
params:
  Country: null
  ExperimentName: null
  ExperimentID: null
  Session: null    
  datadir: '/home/maximilien.chaumon_local/ownCloud/Lab/00-Projects/TimeSocialDistancing/TSDshiny/data'
output:
  html_notebook:
    code_folding: hide
    df_print: paged
    toc: yes
  html_document:
    code_folding: hide
    df_print: paged
    toc: yes
---

```{r, message=F}
source('helpers.R')


```

```{r}
alldata <- gimmeRdata(DataDir = datadir, fast = T, progress = T, as.list = T)

for (i in 1:length(alldata)) {
  alldata[[i]] <- alldata[[i]] %>%
    filter({if ("Trial_Number" %in% names(.)) {Trial_Number == 'END TASK'} else {Question_Key == 'END QUESTIONNAIRE'}})
}
alldata <- bind_rows(alldata)
```


# General count, all countries, Sessions, UniqueNames & Runs

```{r}
count <- alldata %>%
  mutate(Run = str_trunc(Run,1,ellipsis = '')) %>%
  group_by(Country,Session, Run, Unique_Name) %>%
  summarize(N = n()) %>%
  pivot_wider(id_cols = c(Session, Unique_Name, Run), values_from = N, names_from = Country) %>%
  arrange(Session,Unique_Name,Run)
```


```{r}
count %>%
  googlesheets4::write_sheet(ss = 'https://docs.google.com/spreadsheets/d/1ZUvwLJOXNJneGJ2F2SOdWRTsjESctKbtZwqW9T9_A6E', sheet = 'All Sessions')
```

# Attrition figure
```{r}
toplot <- alldata %>% 
  group_by(Country,Session, Participant_Private_ID) %>%
  arrange(UTC_Date) %>%
  group_by(Country, Session, Participant_Private_ID) %>%
  mutate(i = 1:n(), .before = 1) %>%
  group_by(Country,Session, i) %>%
  summarize(n = n())

ggplot(toplot, aes(x = i, y = n, col = Country)) +
  geom_line() +
  # geom_point() +
  # geom_segment(x = 4, xend = 14, y = 1, yend = 1, col = 'black') +
  facet_wrap(~Session, scales = 'free') +
  xlab('Task/Questionnaire order') +
  ylab('N') +
  ggtitle("Participant count across countries and sessions")
```

# Task/Questionnaire order table
```{r}
TaskOrder <- alldata %>% 
  group_by(Country,Session, Participant_Private_ID) %>%
  arrange(UTC_Date) %>%
  mutate(i = 1:n(), .before = 1) %>%
  pivot_wider(id_cols = c(Country, Session, Participant_Private_ID), names_from = i, values_from = Unique_Name) %>%
  arrange(Country,Session)

```


# Participants who signed up to start

```{r}
alldata %>%
  group_by(PID) %>%
  slice(1) %>%
  ungroup() %>%
  summarize(n = n())
```
# Participants who finished Session 1
```{r}
alldata %>%
  group_by(PID, Unique_Name, Session) %>%
  # SemanticTime run 2 is the last task
  filter(Session == 'S1', Unique_Name == 'SemanticTime', Run == 2) %>%
  slice(1) %>%
  group_by() %>%
  summarize(n = n())
```

# Participants who finished Session 2
```{r}
alldata %>%
  group_by(PID, Unique_Name, Session) %>%
  # SemanticTime run 2 is the last task
  filter(Session == 'S2', Unique_Name == 'SemanticTime', Run == 2) %>%
  slice(1) %>%
  group_by() %>%
  summarize(n = n())
```
# Participants who finished Session 3
```{r}
alldata %>%
  group_by(PID, Unique_Name, Session) %>%
  # SelfPercept is the last task
  filter(Session == 'S3', Unique_Name == 'SelfPercept') %>%
  slice(1) %>%
  group_by() %>%
  summarize(n = n())
```
# Participants who finished Session 4
```{r}
alldata %>%
  group_by(PID, Unique_Name, Session) %>%
  filter(Session == 'S4', Unique_Name == 'HADS') %>%
  slice(1) %>%
  group_by() %>%
  summarize(n = n())
```
# Participants who finished Session Control
```{r}
alldata %>%
  group_by(PID, Unique_Name, Session) %>%
  filter(Session == 'SC', Unique_Name == 'END') %>%
  slice(1) %>%
  group_by() %>%
  summarize(n = n())
```

```{r}
toplot <- alldata %>% group_by(PID,Unique_Name,Run,Session) %>%
  filter(`Trial_Number`  =='END TASK' | `Question_Key` == 'END QUESTIONNAIRE') %>%
  ungroup() %>%
  arrange(`UTC_Date`) 


sessionDates <- toplot %>%
  group_by(Session) %>%
  summarize(Start = first(`UTC_Date`),
            Stop = last(`UTC_Date`)) %>%
  select(Session,Start,Stop)

# confinement <- tibble(Date = lubridate::ymd_hms(c('2020/03/17 12:00:00','2020/05/11 23:59:59','2020/10/30 00:00:00', '2020/12/15 23:59:59'),tz = 'CET'), Session = c(1,1,2,2), Begend = c('Start','Stop','Start','Stop')) %>%
#   pivot_wider(values_from=Date,names_from=Begend)

ggplot(toplot,aes(x=`UTC_Date`, y=PID, col=Unique_Name, shape = Session)) +
  geom_point() +
  # geom_ribbon(aes(xmin = Start, xmax = Stop, fill = Session, x = NA, y = NA, col = NA, shape = NA), data=sessionDates) +
  # geom_ribbon(aes(xmin = Start, xmax = Stop,fill=Session, x = NA, y = NA, col = NA, shape = NA), data=confinement) +
  geom_vline(aes(xintercept = Start),linetype = 2,data=sessionDates) +
  geom_vline(aes(xintercept = Stop),linetype = 3,data=sessionDates) +
  theme(axis.text.y = element_blank(),
        axis.ticks.y = element_blank()) +
  xlab('Date') + ylab('Participants')

```


```{r}

count <- tibble()
if ('Trial_Number' %in% colnames(alldata)) {
  count <- filter(alldata,`Trial_Number` == 'END TASK') %>%
    group_by(Country,Session, Run, Unique_Name) %>%
    summarize(N = n()) %>%
    bind_rows(count)
}
if ('Question_Key' %in% colnames(alldata)) {
  count <- filter(alldata,`Question_Key` == 'END QUESTIONNAIRE') %>%
    group_by(Country,Session, Run, Unique_Name) %>%
    summarize(N = n()) %>%
    bind_rows(count)
}

ggplot(count,aes(x=Unique_Name,y=N,fill = Session)) +
  facet_wrap(~ Country, scales = 'free_y') +
  geom_col(position = position_dodge(width = 1)) +
  # geom_label(aes(label=N), position = position_dodge(width = 1), show.legend = F) +
  theme(axis.text.x = element_text(angle = 30,hjust = 1)) +
  labs(x='',y='Count')
```



