---
title: "Time Social Distancing: Shaping data"
output: html_notebook
    
---


This document explains how to extract meaningful data from the tables exported by Gorilla.

First load useful packages and set root directory  (you may have to `install.packages`).
```{r, message=F}

library(tidyverse)
library(plyr)
library(tools)

rootdir = '/home/maximilien.chaumon/ownCloud/Lab/00-Projects/TimeSocialDistancing/DATA'

tmpdir <- file.path(rootdir,'.tmp')

```

## Unzip data
```{r}
datafile <- file.path(rootdir,'DATA ITALY (44pt) update 30_04.zip')

datadir <- sub('.zip','',datafile)

unlink(datadir,recursive=T)

unlink(tmpdir,recursive=T)

unzip(datafile,exdir=tmpdir)
```

## Rename files

Here we turn the file names with node codes to `chk-Checkpoint_tsk-TaskName_v-N.csv`

```{r,warning=F}
fs <- list.files(tmpdir,full.names = T,recursive = T)
dir.create(datadir)
for (f in fs) {
  d <- switch(file_ext(f),
         csv = read_csv(f,col_types = cols()),
         xlsx = readxl::read_excel(f)) %>%
    filter(!is.na(`Task Name`))
  
  if (nrow(d) == 0) {
    print(paste('No data for', basename(f)))
    file.remove(f)
    next
  }
  
  chkpt <- unique(d$Checkpoint) %>%
    gsub(' ','_',.,)
  fn <- unique(d$`Task Name`) %>%
    gsub(' ','_',.,)
  v <- unique(d$`Experiment Version`) %>%
    gsub(' ','_',.,)
  
  write_csv(d, path = file.path(datadir, paste0('chk-',chkpt,'_tsk-',fn,'_v-',v,'.csv')))
  
  file.remove(f)
}

```

## Merge experiment versions

```{r,message=F}
fs <- list.files(datadir,pattern='chk-(.*)_tsk-(.*)_v-(.*).csv',full.names = T) %>%
  tibble(fname=.) %>%
  extract(fname,into=c('Checkpoint','Task Name','Experiment Version'),'chk-(.*)_tsk-(.*)_v-(.*).csv',remove = F) %>%
  group_by(Checkpoint,`Task Name`) %>%
  group_split()


for (f in fs) {
  chkpt <- unique(f$Checkpoint)
  fn <- unique(f$`Task Name`)
  d <- ldply(as.list(f$fname),read_csv) %>%
    bind_rows() %>%
    arrange(`Experiment Version`)
  write_csv(d, path = file.path(datadir, paste0('chk-',chkpt,'_tsk-',fn,'.csv')))
  file.remove(f$fname)
}
```

# Welcome


```{r,message=F}
orig <- read_csv(file.path(datadir,'chk-Session1_confinement_Tasks_3_tsk-00_Welcome.csv'))

orig %>% dplyr::summarise(`Number of subjects` = n(),Consented = sum(consent))

```

# Demographics

```{r, message=F}
orig <- read_csv(file.path(datadir,'chk-Session1_confinement_Tasks_3_tsk-01_Demographics.csv'))

orig %>% dplyr::summarise(meanAge = mean(`dob-year`),
                          sdAge = sd(`dob-year`),
                          propMale = mean(sex=='M'),
                          propRightHand = mean(handedness == 'Destrimane'))

```

