---
title: "Data Unzip"
output:
  html_document:
    code_folding: hide
    df_print: paged
    toc: yes
  html_notebook:
    code_folding: hide
    df_print: paged
    toc: yes
params:
  Country: JP
  ExperimentName: null
  ExperimentID: null
  Session: null    
---

<!-- # This is the Blursday database paper source code. -->
<!-- # This code was used to prepare the following article: -->
<!-- # XXX Ref. to add XXX -->
<!-- # -->
<!-- # The live application of the server can be accessed at  -->
<!-- # https://dnacombo.shinyapps.io/Blursday/ -->
<!-- # This code is publicly available at -->
<!-- # https://github.com/dnacombo/TSDshiny -->

<!-- #     Copyright (C) 2021  Maximilien Chaumon -->
<!-- # -->
<!-- #     This program is free software: you can redistribute it and/or modify -->
<!-- #     it under the terms of the GNU General Public License as published by -->
<!-- #     the Free Software Foundation, either version 3 of the License, or -->
<!-- #     (at your option) any later version. -->
<!-- # -->
<!-- #     This program is distributed in the hope that it will be useful, -->
<!-- #     but WITHOUT ANY WARRANTY; without even the implied warranty of -->
<!-- #     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the -->
<!-- #     GNU General Public License for more details. -->
<!-- # -->
<!-- #     You should have received a copy of the GNU General Public License -->
<!-- #     along with this program.  If not, see <http://www.gnu.org/licenses/>. -->

```{r Prepare, message=FALSE}
# library(tidyverse)
# online <- T
source('helpers.R')
l <- paramsMatch(ExperimentName = params$ExperimentName,
                 ExperimentID = params$ExperimentID,
                 Session = params$Session,
                 Country = params$Country, 
                 experimentIDs = ExperimentIDs)

dum <- list2env(l, envir = environment())
```

### list and unzip files

```{r list and unzip files, message=F}

# list files
zipfiles <- unlist(sapply(ExperimentID,function(f){list.files(dirData,paste0('data_exp_',f,'-v.*.zip'),full.names = T)}))

# create temp dir
tmpdir <- file.path(dirData,'.tmp',paste0(sample(LETTERS,10), collapse = ''))
# remove any preexisting data
unlink(tmpdir,recursive=T)

cat('Unzipping files:\n')
cat(basename(zipfiles),sep = '\n')
dum <- sapply(zipfiles,function(x){unzip(x,exdir=tmpdir)})

# output directory is the zip filename plus experiment name and session
sessiondatadir <- character()
for (S in Session) {
  m <- paramsMatch(ExperimentName = ExperimentName, ExperimentID = ExperimentID, Session = S, experimentIDs = ExperimentIDs)
  sessiondatadir[S] <- file.path(dirData,paste0('data_exp_',paste(as.character(m$ExperimentID),collapse = '-'), '_', m$ExperimentName[1], '_Session',S))
}

# remove eventual previous output in that directory
unlink(sessiondatadir,recursive=T)

```

The text below shows csv files that are missing from [this google sheet](https://docs.google.com/spreadsheets/d/1Mwy2aGCJ6vSpp4a32NOs83e2H73MQRFUOL_193yb8sQ/edit#gid=0).

**These tasks/questionnaires will not be present in the output:**


```{r locate and expand UniqueNames,warning=F}
fs <- list.files(tmpdir,full.names = T,recursive = T)
dum <- sapply(sessiondatadir,dir.create)

for (f in fs) {
  eid <- str_replace(f,'.*\\.tmp/[A-Z]*/data_exp_([0-9]{5}).*','\\1')
  l <- paramsMatch(ExperimentID = eid,experimentIDs = ExperimentIDs)
  # if (grepl('data_exp_16346.*bc7r',f)) {stop()}
  if (file.size(f) < 400) {
    file.remove(f)
    next
  }
  d <- switch(tools::file_ext(f),
              csv = suppressWarnings(read_csv(f,col_types = cols(.default = col_character()))),
              xlsx = readxl::read_excel(f)) %>%
    filter(!is.na(`Task Name`))
  # print(f)
  
  if (nrow(d) == 0) {
    # cat(paste('No data for', basename(f)),sep='\n')
    file.remove(f)
    next
  } 
  
  CurrNode <- filter(allnodes, Session == l$Session, get(l$ExperimentName) == gsub('.*-([[:alnum:]]{4})', '\\1', unique(d$`Tree Node Key`)))
  if (nrow(CurrNode) > 1) {
    cat(paste('###### Several UniqueNames for', basename(f), '?!? ', ':', unique(d$`Task Name`)),sep='\n')
    dum <- file.remove(f)
    next
  }
  
  if (nrow(CurrNode) == 0 ){
    cat(paste('###### Could not locate UniqueName for',basename(f), ':', unique(d$`Task Name`)),sep='\n')
    dum <- file.remove(f)
    next
  }
  
  fw <- file.path(sessiondatadir[str_detect(sessiondatadir,eid)], paste0(CurrNode$UniqueName, '_v-', unique(d$`Experiment Version`), '.csv'))
  if (file.exists(fw)) {
    d <- read_csv(fw,col_types = cols(.default = col_character())) %>%
      bind_rows(d)
  }
  dum <- write_csv(d, file = fw)
  # cat(paste0(basename(f),' --> ', basename(fw), ': OK'), sep = '\n')
  
  dum <- file.remove(f)
}

```

**Output files created:**

```{r merge versions, message=F}
fs <- list.files(sessiondatadir,pattern='([^\\/]*)_v-(.*).csv',full.names = T) %>%
  tibble(fname=.) %>%
  extract(fname,into=c('UniqueName','Experiment Version'),'([^\\/]*)_v-(.*).csv',remove = F) %>%
  group_by(UniqueName) %>%
  group_split()


for (f in fs) {
  fn <- unique(f$UniqueName)
  d <- plyr::ldply(as.list(f$fname),function(f){suppressWarnings(read_csv(f,col_types=cols()))}) %>%
    bind_rows() %>%
    arrange(`Experiment Version`) %>%
    mutate(PID = `Participant Private ID`)
  
  write_csv(d, file = file.path(unique(dirname(f$fname)), paste0(fn,'.csv')))
  
  cat(paste0(fn,'.csv'),sep='\n')
  file.remove(f$fname)
}
```

<!-- ### Storing column names in a table -->

<!-- Storing the results in `ColumnNames.csv` -->

<!-- ```{r} -->
<!-- for (dr in sessiondatadir) { -->
<!--   fs <- list.files(dr,pattern='([^\\/]*).csv',full.names = T) %>% -->
<!--     tibble(fname=.) %>% -->
<!--     extract(fname,into=c('UniqueName'),'([^\\/]*).csv',remove = F) %>% -->
<!--     group_by(UniqueName) %>% -->
<!--     group_split() -->

<!--   d <- tibble() -->
<!--   for (f in fs) { -->
<!--     # get column names into a column -->
<!--     # print(f) -->
<!--     d <- suppressWarnings(read_csv(f$fname, col_types = cols(), n_max = 1)) %>% -->
<!--       colnames() %>% -->
<!--       tibble(Column = .) %>% -->
<!--       mutate(ExperimentID = paste(ExperimentID,collapse='-'), -->
<!--              UniqueName = f$UniqueName, -->
<!--              ColNum = 1:nrow(.)) %>% -->
<!--       bind_rows(d) -->
<!--   } -->

<!--   if (nrow(d) >0){ -->
<!--     extraColumnNames <- d %>% filter(!ColNum %in% seq(1,26), -->
<!--                                      !str_detect(Column,'(order|checkpoint|branch)')) -->
<!--     ColumnNames <- d %>% -->
<!--       pivot_wider(values_from = c('Column'),names_from = c('ExperimentID','UniqueName'),values_fn = list(Column = first)) -->

<!--     write_csv(ColumnNames,file = file.path(dr,'ColumnNames.csv'),na = '') -->
<!--     (ColumnNames) -->
<!--   } -->
<!-- } -->
<!-- ``` -->

<!-- ```{r} -->

<!-- if ( !file.exists(f <- file.path(sessiondatadir[1],'extraColumnNames.csv'))){ -->
<!--   allColumnNames <- extraColumnNames %>% -->
<!--     write_csv(f) -->
<!-- } else { -->
<!--   # read all colum names in all seen experiments so far -->
<!--   allColumnNames <- suppressWarnings(read_csv(file = f,col_types = cols())) %>% -->
<!--     mutate(ExperimentID = as.character(ExperimentID)) %>% -->
<!--     # if ExperimentID exists already, update with current ColumnNames -->
<!--     filter( ExperimentID != paste(ExperimentID,collapse='-')) %>% -->
<!--     bind_rows(extraColumnNames) %>% -->
<!--     write_csv(f) -->
<!-- } -->

<!-- # allColumnNames %>% -->
<!-- #   group_by(ColNum,UniqueName) %>% -->
<!-- #   summarize(n = n()) %>% -->
<!-- #   ungroup() %>% -->
<!-- #   summarize(`NExperiments` = unique(n)) -->

<!-- ``` -->


<!-- ### for questionnaires, storing question names in a table -->

<!-- Storing the results in `QuestionKeys.csv` -->

<!-- ```{r, warning=F} -->

<!-- for (dr in sessiondatadir) { -->
<!--   fs <- list.files(dr,pattern='(S[^\\/]*).csv',full.names = T) %>% -->
<!--     tibble(fname=.) %>% -->
<!--     extract(fname,into=c('UniqueName'),'([^\\/]*).csv',remove = F) %>% -->
<!--     group_by(UniqueName) %>% -->
<!--     group_split() -->


<!--   d <- tibble() -->
<!--   for (f in fs) { -->
<!--     # get column names into a column -->
<!--     # print(f) -->
<!--     tmp <- suppressWarnings(read_csv(f$fname, col_types = cols())) -->
<!--     if (length(unique(tmp$`Tree Node Key`)) > 1) { -->
<!--       cat('Warning, it seems that there are more keynodes than expected associated with this file. Check NodeKeys!') -->
<!--       cat(f$fname, sep = '\n')  -->
<!--       cat(unique(tmp$`Tree Node Key`), sep = '\n') -->
<!--       next} -->
<!--     if (startsWith(unique(tmp$`Tree Node Key`),'task')) next -->

<!--     d <- tibble(Question = unique(tmp$`Question Key`)) %>% -->
<!--       mutate(ExperimentID = paste(ExperimentID,collapse = '-'), -->
<!--              UniqueName = f$UniqueName, -->
<!--              KeyNum = 1:nrow(.)) %>% -->
<!--       bind_rows(d) -->

<!--   } -->

<!--   if (nrow(d) >0){ -->
<!--     QuestionKeys <- d %>% -->
<!--       pivot_wider(values_from = c('Question'),names_from = c('ExperimentID','UniqueName'),values_fn = list(Column = first)) -->
<!--     write_csv(QuestionKeys,file = file.path(dr,'QuestionKeys.csv'),na = '') -->
<!--     (QuestionKeys) -->
<!--   } -->
<!-- } -->

<!-- ``` -->



