---
title: "Date layout"
params:
  Country: null
  ExperimentName: null
  ExperimentID: null
  Session: null    
  datadir: '/home/maximilien.chaumon_local/ownCloud/Lab/00-Projects/TimeSocialDistancing/TSDshiny/data'
output:
  html_document: 
    code_folding: hide
    df_print: paged
    toc: yes
---



```{r}
source('helpers.R')
library(DT)

# l <- paramsMatch(Country = params$Country,experimentIDs = ExperimentIDs)
# l$datadir <- params$datadir
# l <- as_tibble(l)
# 
# alldata <- gimmeRdata(params$datadir, fast = T, progress = T)
# save(alldata, file = 'AllData.RData')

load(file = 'AllData.RData')
```

## Counting subjects
```{r}
count <- alldata %>% 
  filter(`Trial_Number`  =='END TASK' | `Question_Key` == 'END QUESTIONNAIRE') %>%
    group_by(Country,Session, Run,  Unique_Name) %>%
    summarize(N = n())

ggplot(count,aes(x = Unique_Name,y=N,fill = Session)) +
  facet_grid(Country~Session) +
  geom_col(position = position_dodge(width = 1)) +
  # geom_label(aes(label=N), position = position_dodge(width = 1), show.legend = F) +
  theme(axis.text.x = element_text(angle = 30,hjust = 1)) +
  labs(x='',y='Count')
```

```{r}
count %>%
  pivot_wider(id_cols = c(Session,Run,Unique_Name), names_from = Country, values_from=N) 
```

## Tasks, dates, and PID

Finishing times sorted by Participant and completion date.

<!-- ```{r include = FALSE} -->
<!-- # Why, oh why do I need this chunk? -->
<!-- datatable(NULL) -->
<!-- ``` -->

<!-- ```{r results='asis'} -->

<!-- allPIDs <- alldata %>% group_by(`Participant_Private_ID`) %>% -->
<!--   filter(`Trial_Number`  =='END TASK' | `Question_Key` == 'END QUESTIONNAIRE') %>% -->
<!--   pivot_wider(c(PID, Unique_Name, Run, Session, `UTC_Date`),names_from = Session, values_from = `Participant_Private_ID`, values_fn = function(x){paste(x,collapse=' ')}) %>% -->
<!--   arrange(PID, `UTC_Date`) %>% -->
<!--   mutate(`UTC_Date` = lubridate::ymd_hms(`UTC_Date`)) %>% -->
<!--   select(`UTC_Date`,Unique_Name, Run, PID, starts_with('S')) %>% -->
<!--   datatable() %>% -->
<!--   htmltools::tagList() %>% -->
<!--   print() -->


<!-- ``` -->


The dashed and dotted lines highlight the first and last points of each of the three sessions.

```{r, fig.width=20, fig.height=10}
toplot <- alldata %>% group_by(PID,Unique_Name,Run,Session) %>%
  filter(`Trial_Number`  =='END TASK' | `Question_Key` == 'END QUESTIONNAIRE') %>%
  arrange(`UTC_Date`) 


sessionDates <- toplot %>%
  group_by(Session) %>%
  summarize(Start = first(`UTC_Date`),
         Stop = last(`UTC_Date`)) %>%
  select(Session,Start,Stop)

# confinement <- tibble(Date = lubridate::ymd_hms(c('2020/03/17 12:00:00','2020/05/11 23:59:59','2020/10/30 00:00:00', '2020/12/15 23:59:59'),tz = 'CET'), Session = c(1,1,2,2), Begend = c('Start','Stop','Start','Stop')) %>%
#   pivot_wider(values_from=Date,names_from=Begend)

ggplot(toplot,aes(x=`UTC_Date`, y=PID, col=Unique_Name, shape = Session)) +
  geom_point() +
  # geom_ribbon(aes(xmin = Start, xmax = Stop, fill = Session, x = NA, y = NA, col = NA, shape = NA), data=sessionDates) +
  # geom_ribbon(aes(xmin = Start, xmax = Stop,fill=Session, x = NA, y = NA, col = NA, shape = NA), data=confinement) +
  # geom_vline(aes(xintercept = Start),linetype = 2,data=sessionDates) +
  # geom_vline(aes(xintercept = Stop),linetype = 3,data=sessionDates) +
  theme(axis.text.y = element_blank(),
        axis.ticks.y = element_blank(),
        panel.background = element_blank(), 
        strip.background = element_blank(),
        # panel.grid.major = element_line(colour = 'grey80')
        ) +
  facet_wrap(~Country, scales = 'free_y') +
  xlab('Date') + ylab('Participants')
```
```{r, fig.width=20, fig.height=10}
toplot <- alldata %>% add_StringencyIndex() %>% group_by(PID,Unique_Name,Run,Session, Stringency_Index) %>%
  filter(`Trial_Number`  =='END TASK' | `Question_Key` == 'END QUESTIONNAIRE') %>%
  arrange(`UTC_Date`) %>%
  group_by(PID, Session) %>%
  slice(1,n()) %>%
  mutate(i = c('dbeg','dend')) %>%
  pivot_wider(id_cols = c(Country,PID, Session),names_from = i, values_from = UTC_Date)


ggplot(toplot,aes(x = dbeg, xend = dend, y=PID, yend=PID, col=Session)) +
  geom_segment() +
  geom_point(aes(x=Local_Date, y = Stringency_Index))
  # geom_ribbon(aes(xmin = Start, xmax = Stop, fill = Session, x = NA, y = NA, col = NA, shape = NA), data=sessionDates) +
  # geom_ribbon(aes(xmin = Start, xmax = Stop,fill=Session, x = NA, y = NA, col = NA, shape = NA), data=confinement) +
  # geom_vline(aes(xintercept = Start),linetype = 2,data=sessionDates) +
  # geom_vline(aes(xintercept = Stop),linetype = 3,data=sessionDates) +
  theme(axis.text.y = element_blank(),
        axis.ticks.y = element_blank(),
        axis.text.x = element_text(angle = 30, hjust = 1),
        panel.background = element_blank(), 
        strip.background = element_rect(fill = NA, linetype = 1, colour = 'black'),
        
        # panel.grid.major = element_line(colour = 'grey80')
        ) +
  facet_wrap(~Country, scales = 'free_y', switch = 'y') +
  xlab('Date') + ylab('Participants') +
  scale_x_datetime(date_breaks = '1 week')
```