---
title: "General Demographics"
params:
  Country: null
  ExperimentName: null
  ExperimentID: null
  Session: null    
  datadir: '/home/maximilien.chaumon/ownCloud/Lab/00-Projects/TimeSocialDistancing/DATA'
output:
  html_document:
    code_folding: hide
    df_print: paged
    toc: yes
  html_notebook:
    code_folding: hide
    df_print: paged
    toc: yes
---

```{r, message = F}

source('helpers.R')
library(lubridate)
l <- paramsMatch(params,
                 experimentIDs = ExperimentIDs)
l$datadir <- params$datadir

demo <- gimmedata(DataDir = datadir, ExperimentID = paste(l$ExperimentID,collapse='|'), UniqueName = 'Demographics', verbose = F) %>%
  mutate(Country = recode(`Experiment ID`,!!!l$Country),.before = 1)

gsheet2tbl <- function (url) {
  read_csv(file=gsheet::gsheet2text(url, format='csv'), col_types = cols(.default = col_character()))
}

Keys <- gsheet2tbl('https://docs.google.com/spreadsheets/d/1bwKj-ngDrHFVXpSD13l183FHsXoZu1HqQmz9ZtYROYM/edit#gid=1012544807') %>%
  filter(UniqueName == 'Demographics')

recoder <- Keys$Standard
names(recoder) <- Keys$Question

HandednessMap <- read_csv('Δεξιόχειρας,right-handed
Αριστερόχειρας,left-handed
Αμφιδέξιος,ambidextrous
Sağlak,right-handed
İki elini de kullanabilen,ambidextrous
Solak,left-handed
Derecha,right-handed
Right-handed,right-handed
Left-handed,left-handed
Ambidextrous,ambidextrous
Rechtshändig,right-handed
Linkshändig,left-handed
Beidhändig,ambidextrous
右利き,right-handed
左利き,left-handed
両利き,ambidextrous
Droite,right-handed
Gauche,left-handed
Ambidextre,ambidextrous
Ambidestro,ambidextrous
Ambidiestro,ambidextrous
Destrimane,right-handed
Izquierda,left-handed
Mancino,left-handed', col_names = F)
recodeHandedness <- HandednessMap$X2
names(recodeHandedness) <- HandednessMap$X1

Demo <- demo %>%
  mutate(`Question Key` = recode(`Question Key`,!!!recoder)) %>%
  select(`Experiment ID`, `PID`, Session, `Question Key`, `Response`, `UTC Date`) %>%
  group_by(`Experiment ID`) %>%
  mutate(Country = as.factor(ID2Country(`Experiment ID`,ExperimentIDs = ExperimentIDs))) %>%
  ungroup() %>%
  mutate(`Question Key` = recode(`Question Key`,
                                 `dob-year` = "Age-year",
                                 `dob-month` = "Age-month")) %>%
  filter(`Question Key` %in% c("Age-year", "Age-month", "sex-quantised", "Handedness", "DOB")) %>%
  mutate(`UTC Date` = floor_date(ymd_hms(`UTC Date`), unit = 'days')) %>%
  pivot_wider(id_cols = c(Country,Session,PID, `UTC Date`), values_from = Response, names_from = `Question Key`, values_fn = first) %>%
  mutate(Sex = as.factor(recode(`sex-quantised`,`1`='M',`2`='F',`2`='W')),
         Handedness = as.factor(recode(Handedness,!!!recodeHandedness)),
         Age = as.numeric(dyears(abs(as.numeric(`Age-year`))) + dmonths(abs(as.numeric(`Age-month`))),'years'),
         DOB2 =  floor_date(`UTC Date` - dyears(Age), unit = 'days'))
Demo$DOB2[is.na(Demo$DOB2)] <- parse_date_time(Demo$DOB[is.na(Demo$DOB2)],orders = '%d.%m.%y',truncated = 1)
Demo <- Demo %>%
  select(-DOB) %>%
  rename(DOB = DOB2) %>%
  mutate(Age = as.numeric(as.period(interval(end=as.Date(`UTC Date`), start = as.Date(DOB))),'years'),
         Age = ifelse(between(Age,5,90),Age,NA),
         Age = round(Age, digits = 1),
         Session = as.factor(Session),
         PID = as.factor(PID)) %>%
  select(-`Age-month`, -`Age-year`, -`sex-quantised`) %>%
  write_csv(file.path(params$datadir,'Demographics.csv'), na = '') %>%
  save(Demo,file = file.path(params$datadir,'Demographics.RData'))

# %>%
#   select(Country,Session,PID,`UTC Date`,Age, Sex, Handedness)
```
```{r}
skimr::skim(Demo)
```

```{r}

ggplot(Demo,aes(x=Age,fill=Country)) +
  geom_histogram(position = 'dodge',bins = 30, show.legend = F) + 
  facet_wrap(~Country, scales = 'free_y') +
  xlim(0,80) + 
  ggtitle('Age distribution across countries')

library(ggridges)
ggplot(Demo, aes(y= Country, x= Age,  fill= Country)) +
  geom_density_ridges(alpha=0.6) +
  theme_ridges() +
  theme(legend.position="none",
        strip.text.x = element_text(size = 8)) +
  labs(y = "Country", x = "Age", title ="Age distributions of participants") +
  theme(plot.title = element_text(face = "bold", "hjust" = 0.5)) +
  scale_x_continuous(breaks = seq(from = 0, to = 80, by = 5))

Demo %>% group_by(Country) %>%
  mutate(n=n()) %>%
  group_by(Country,Handedness) %>%
  summarize(H = n()/n) %>% distinct() %>%
  ggplot(aes(x=Country,y=H,fill=Handedness)) +
  geom_col()  +
  ggtitle('Handedness proportions across countries')

Demo %>% group_by(Country) %>%
  mutate(n=n()) %>%
  group_by(Country,Sex) %>%
  summarize(S = n()/n) %>% distinct() %>%
  ggplot(aes(x=Country,y=S,fill=Sex)) +
  geom_col()  +
  ggtitle('Sex proportions across countries')

```
