---
title: "Extracting data for Questionnaire Demographics"
params:
  ExperimentID: [15096,16303]
  rootdir: /home/maximilien.chaumon/ownCloud/Lab/00-Projects/TimeSocialDistancing/DATA
output:
  html_document:
    df_print: paged
    toc: yes
  html_notebook:
    code_folding: hide
    toc: yes
---



```{r, message=F}
library(tidyverse)
library(ggbeeswarm)
source('helpers.R')
```

```{r, message=F}

datadir = file.path(params$rootdir,paste0('data_exp_', paste(ExperimentID,collapse='-'), '_', ExperimentName[1]))
outdir = paste(datadir,'processed',sep='_')
dir.create(outdir,showWarnings = F)

datafile <- list.files(datadir,'S1_Demographics.csv',full.names = T)

tmpdir <- file.path(params$rootdir,'.tmp')
unlink(tmpdir,recursive=T)

if (is_empty(datafile)){
  print('No Demographics data')
  knitr::knit_exit()
  }

```

### Read and describe data

```{r, warning=F}

orig <- Q_read(datafile)

N <- Q_Nsuj(orig)


```

Number of participants who completed this questionnaire:
`r N`

```{r}

Q_Complete(orig)

```

### Questionnaire scores

```{r}

# this function will help reverse scores
R <- function(x) {7 - x}

(data_in_shape <- orig %>%
  select(`Participant Private ID`,`Local Date`,
         `Question Key`, Response) %>%
  filter(grepl('-quantised',x=`Question Key`)) %>%
  mutate(`Question Key` = as.factor(str_replace(`Question Key`,"ASQ_([0-9]+)-quantised",'Q\\1')),
         Response = as.numeric(Response),
         `Local Date` = parse_datetime(`Local Date`,format = '%d/%m/%Y %H:%M:%S'),
         `WeekDay` = lubridate::wday(`Local Date`)) %>%
  pivot_wider(names_from = `Question Key`,values_from = Response) %>%
    mutate(Score = Q01 + Q02 + Q03 + R(Q04) + R(Q05) + R(Q06) + Q07 + Q08 +
             Q09 + R(Q10) + R(Q11) + Q12 + Q13 + R(Q14) + R(Q15) + Q16 + Q17) %>%
  select(-starts_with('Q'))
  ) %>%
  write_csv(file.path(outdir,basename(datafile)))
```


```{r}
ggplot(data_in_shape,aes(x=WeekDay,y=Score,col=`Participant Private ID`)) +
  geom_beeswarm()
```