---
title: "Extracting data for Questionnaire HADS"
params:
  experimentID: 16144
output:
  html_document:
    df_print: paged
    toc: yes
  html_notebook:
    code_folding: hide
    toc: yes
---

<!-- # This is the Blursday database paper source code. -->
<!-- # This code was used to prepare the following article: -->
<!-- # XXX Ref. to add XXX -->
<!-- # -->
<!-- # The live application of the server can be accessed at  -->
<!-- # https://dnacombo.shinyapps.io/Blursday/ -->
<!-- # This code is publicly available at -->
<!-- # https://github.com/dnacombo/TSDshiny -->

<!-- #     Copyright (C) 2021  Maximilien Chaumon -->
<!-- # -->
<!-- #     This program is free software: you can redistribute it and/or modify -->
<!-- #     it under the terms of the GNU General Public License as published by -->
<!-- #     the Free Software Foundation, either version 3 of the License, or -->
<!-- #     (at your option) any later version. -->
<!-- # -->
<!-- #     This program is distributed in the hope that it will be useful, -->
<!-- #     but WITHOUT ANY WARRANTY; without even the implied warranty of -->
<!-- #     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the -->
<!-- #     GNU General Public License for more details. -->
<!-- # -->
<!-- #     You should have received a copy of the GNU General Public License -->
<!-- #     along with this program.  If not, see <http://www.gnu.org/licenses/>. -->


```{r, message=F}
library(tidyverse)
source('helpers.R')
```

```{r, message=F}

datadir = file.path(dirData,paste0('data_exp_', paste(params$experimentID,collapse='-'), '_', ExperimentName[1]))
outdir = paste(datadir,'processed',sep='_')
dir.create(outdir,showWarnings = F)

experimentID <- unique(gsub('.*data_exp_([[:digit:]]+)','\\1',datadir))

datafiles <- list.files(datadir,'S1_HADS_r.*.csv',full.names = T)

tmpdir <- file.path(dirData,'.tmp')
unlink(tmpdir,recursive=T)

if (is_empty(datafiles)){
  print('No HADS data')
  knitr::knit_exit()
  }

```

### Read and describe data

```{r}
orig <- Q_read(datafiles) %>%
  mutate(Run = as.factor(str_replace(File,'S._HADS_r(.).csv','\\1')))
N <- Q_Nsuj(orig)


```

Number of participants who completed this questionnaire:
`r N`

```{r}

Q_Complete(orig)

```

## Questionnaire scores

```{r}

# Scoring for each item is annotated next to the response and can be 0,1, 2 or 3
# Sum scores for each of the seven items HADS_A (anxiety score) separately from the HADS_D (depression score)

(data_in_shape <- orig %>%
  select(`Participant Private ID`,`Local Date`, Run,
         `Question Key`, Response) %>%
   filter(grepl('HADS_[AD]',x=`Question Key`)) %>%
  mutate(HADS = as.factor(str_replace(`Question Key`,"HADS_([AD]).*",'\\1')),
         Response = as.numeric(str_replace(Response,"([0-3]) ?- .*",'\\1')),
         `Local Date` = parse_datetime(`Local Date`,format = '%d/%m/%Y %H:%M:%S'),
         `WeekDay` = lubridate::wday(`Local Date`)) %>%
   group_by(`Participant Private ID`,HADS,Run) %>% 
   dplyr::summarize(Score = sum(Response))
) %>% write_csv(file.path(outdir,'S1_HADS.csv'))

```


```{r}
ggplot(data_in_shape,aes(x=Run,y=Score,fill=HADS)) +
  geom_col(position = 'dodge') +
  # coord_polar() +
  facet_wrap(~`Participant Private ID`)
```