---
title: "Extracting data for Task Delay Discouting"
params:
  Country: TR
  ExperimentName: null
  ExperimentID: null
  Session: null    
output:
  html_document:
    code_folding: hide
    df_print: paged
    toc: yes
  html_notebook:
    code_folding: hide
    toc: yes
---
<!-- # This is the Blursday database paper source code. -->
<!-- # This code was used to prepare the following article: -->
<!-- # XXX Ref. to add XXX -->
<!-- # -->
<!-- # The live application of the server can be accessed at  -->
<!-- # https://dnacombo.shinyapps.io/Blursday/ -->
<!-- # This code is publicly available at -->
<!-- # https://github.com/dnacombo/TSDshiny -->

<!-- #     Copyright (C) 2021  Maximilien Chaumon -->
<!-- # -->
<!-- #     This program is free software: you can redistribute it and/or modify -->
<!-- #     it under the terms of the GNU General Public License as published by -->
<!-- #     the Free Software Foundation, either version 3 of the License, or -->
<!-- #     (at your option) any later version. -->
<!-- # -->
<!-- #     This program is distributed in the hope that it will be useful, -->
<!-- #     but WITHOUT ANY WARRANTY; without even the implied warranty of -->
<!-- #     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the -->
<!-- #     GNU General Public License for more details. -->
<!-- # -->
<!-- #     You should have received a copy of the GNU General Public License -->
<!-- #     along with this program.  If not, see <http://www.gnu.org/licenses/>. -->

```{r, message=F}
# load a few helpers functions and variables
source('helpers.R')

# find out which experiment name, ID, session... we're talking about
l <- paramsMatch(params,
                 experimentIDs = ExperimentIDs)

library(ggbeeswarm)
library(ggrepel)
library(afex)
library(skimr)
```


```{r, message=F}

datadir = file.path(dirData,paste0('data_exp_', paste(params$experimentID,collapse='-'), '_', ExperimentName[1]))
outdir = paste(datadir,'processed',sep='_')
dir.create(outdir,showWarnings = F)

experimentID <- params$experimentID

datafiles <- list.files(datadir,'S1_DelayDiscount_r.*.csv',full.names = T)

tmpdir <- file.path(dirData,'.tmp')
unlink(tmpdir,recursive=T)

if (is_empty(datafiles)){
  print('No DelayDiscount data')
  knitr::knit_exit()
  }


```

### Read and describe data

```{r, warning=F}

orig <- T_read(datafiles) %>%
  mutate(Run = as.factor(str_replace(File,'S._DelayDiscount_r(.).csv','\\1')))

N <- T_Nsuj(orig)


```

Number of participants who completed this task:
`r N`

```{r}

T_Complete(orig)

```

### Extracting data

```{r}

data_in_shape <- orig %>%
  mutate(Response = ifelse(str_detect(Response,'now'),'immediate','delayed')) %>%
  extract(Amount1,c('A1','D1'),regex = '.*? ?([[:digit:]]+) (.*)',remove = F) %>%
  extract(Amount2,c('A2','D2'),regex = '.*? ?([[:digit:]]+) (.*)',remove = F) %>%
  mutate_at(.vars=c('D1','D2'),function(x){as.numeric(ifelse(str_detect(x,'[[:digit:]]'),str_extract(x,'[[:digit:]]+'),'0'))}) %>%
  mutate(Delay = abs(D2-D1),
         A1 = as.numeric(A1),A2 = as.numeric(A2),
         AmountDiff = abs(A2-A1)
         ) %>%
  select(`Participant Private ID`,`Local Date`,
         Response,Delay,AmountDiff,Run) %>%
  filter(!is.na(Delay)) %>%
  write_csv(file.path(outdir,'S1_DelayDiscount.csv'))
```


```{r}
data_in_shape %>%
  mutate(Response = recode(Response,immediate = 0,delayed = 1)) %>%
  group_by(`Participant Private ID`,Delay,Run) %>%
  dplyr::summarize(AmountDiff = mean(AmountDiff),
                   meanResponse = mean(Response)) %>%
ggplot(aes(x=Delay,y=meanResponse,col=`Participant Private ID`,group=`Participant Private ID`)) +
  geom_point() +
  geom_line() +
  facet_wrap(~Run,labeller='label_both')
```