---
title: "Extracting data for Task Implicit Timing"
params:
  Country: null
  ExperimentName: null
  ExperimentID: null
  Session: null    
output:
  html_document:
    code_folding: hide
    df_print: paged
    toc: yes
  html_notebook:
    code_folding: hide
    toc: yes
---


```{r, message=F}
# load a few helpers functions and variables
source('helpers.R')

# find out which experiment name, ID, session... we're talking about
l <- paramsMatch(params,
                 experimentIDs = ExperimentIDs)

library(ggbeeswarm)
library(ggrepel)
library(afex)
library(skimr)
```

## Read and describe data

```{r, rows.print = 100}

  orig <- gimmedata(dirData, ExperimentID = paste(l$ExperimentID,collapse='|'), UniqueName = 'Implicit', verbose = F, progress = F) %>%
    mutate(`Reaction Time` = as.numeric(`Reaction Time`),
           Session = as.factor(Session),
           UniqueName = as.factor(UniqueName),
           Run = as.factor(Run),
           PID = as.factor(PID),
           Country = recode(`Experiment ID`,!!!l$Country))

skim(orig)
```

Number of subjects per Session and Run.

```{r, rows.print = 100}
(N <- orig %>% filter(`Trial Number` %in% 'END TASK') %>%
    select(Country,PID,Session,Run,UniqueName,`Repeat Key`) %>%
    group_by(Country,Session,Run,UniqueName) %>%
    distinct() %>%
    summarize(N = n()))

```

#

```{r}

durations <- T_Complete(orig)

data_duration_filtered <- left_join(orig, durations, by = c('Country',"Session", "UniqueName", "Run", "Experiment ID", "Repeat Key", "Participant Private ID")) %>%
  filter(between(Duration,150,900))

ggplot(durations,aes(x=Duration,fill=Country)) +
  geom_histogram(bins = 100) +
  scale_x_log10() + 
  geom_vline(xintercept = 150) +
  geom_vline(xintercept = 900)

ggplot(data_duration_filtered,aes(x=Duration)) + 
  geom_histogram(bins = 100) +
  scale_x_log10() + 
  geom_vline(xintercept = 150) +
  geom_vline(xintercept = 900)

# ggplot(data_duration_filtered%>%
#          filter(`Trial Number` %in% 'END TASK') %>%
#          group_by(Session,Run, UniqueName,`Experiment ID`,`Repeat Key`) %>%
#          mutate(Duration = as.numeric(`Reaction Time`)/1000),
#        aes(x = `Participant Private ID`, y = Duration,fill= `Participant Private ID`)) +
#   geom_col(show.legend = F) +
#   theme(axis.text.x = element_text(angle = 30,hjust = 1)) +
#   facet_grid(Session~Run) +
#   ylab('Time to complete (s, log scale)') +
#   scale_y_continuous()

```

### Extracting data

```{r}

(data_in_shape <- data_duration_filtered %>%
   filter(display == 'trial',`Zone Type` == 'response_keyboard_single') %>%
   mutate(SOA = factor(SOA,levels=c('500','1750','3000')),
          condition = factor(condition,levels=c(0,1),labels=c('nonPred','Pred'))) %>%
   select(Country,`Participant Private ID`,PID,`Local Date`,
          SOA,condition,Run,`Reaction Time`,`Task Version`, `Experiment ID`,`Repeat Key`,
          Session, randomise_blocks))
# %>%
#   write_csv(file.path(outdir,'S1_ImplicitTiming.csv'))
```


```{r}
ggplot(data_in_shape,aes(x=SOA,y=`Reaction Time`,col=condition,group=interaction(condition,SOA))) +
  geom_boxplot() +
  facet_wrap(~Country)
```

Lots of NA values for condition. What happened?

```{r}
data_in_shape %>% filter(is.na(condition)) %>% group_by(`Participant Private ID`) %>%
  summarize(n = n(),
            version = first(`Task Version`),
            ExperimentID = first(`Experiment ID`))
```

These are the problematic subjects. All from task version 5 ExperimentID 15096.

We now retrieve condition by looking at blocks of 9 trials and checking whether or not the SOA is constant (condition==1 Pred), or variable (condition = 0 non PRed).

```{r}
data_in_shape <- data_in_shape %>% 
  group_by(`Participant Private ID`,`Repeat Key`,randomise_blocks) %>%
  group_modify(.f = function(.x,...){mutate(.x,condition = ifelse(length(unique(.x$SOA)) == 1,'Pred','nonPred'))})

```

```{r}

data_in_shape <- filter(data_in_shape,
                        !is.na(condition),
                        `Reaction Time` > 0)


ggplot(data_in_shape,aes(x=SOA,y=`Reaction Time`,col=condition,group=interaction(condition,SOA))) +
  geom_boxplot() +
  facet_wrap(~Country)

```


```{r}
data_in_shape %>% 
  group_by(Country,`Participant Private ID`, condition, SOA) %>%
  summarize(meanRT = mean(`Reaction Time`)) %>%
  group_by(Country,condition, SOA) %>%
  summarize(n = n(),
            semRT = sd(meanRT) / sqrt(n),
            meanRT = mean(meanRT)) %>%
  ggplot(aes(x=SOA,y=meanRT,col=condition,group=interaction(condition,SOA),ymin = meanRT - semRT, ymax = meanRT + semRT)) +
  geom_pointrange() +
  facet_wrap(~Country)

```

```{r}
library(lme4)
library(lmerTest)
library(emmeans)

data_tostat <- data_in_shape %>%
  filter(Country == 'FR')

m <- lmer(log10(`Reaction Time`) ~ Session * condition * SOA + (1 | `Participant Private ID`), data_tostat )

anova(m)

em <- summary(emmeans(m,specs = ~ condition + SOA + Session),type = 'response',bias.adj = T)

data_in_shape %>% 
  group_by(`Participant Private ID`, condition, SOA, Session) %>%
  summarize(meanRT = mean(`Reaction Time`)) %>%
  group_by(condition, SOA, Session) %>%
  summarize(n = n(),
            semRT = sd(meanRT) / sqrt(n),
            meanRT = mean(meanRT)) %>%
  ggplot(aes(x=SOA,y=meanRT,col=condition,group=interaction(condition,SOA),ymin = meanRT - semRT, ymax = meanRT + semRT)) +
  geom_pointrange(position=position_dodge(.5)) +
  facet_wrap(~Session) +
  geom_text_repel(aes(label = n, col = NA),position=position_dodge(.5))
# + 
#   geom_pointrange(data = em, aes(y=response,ymin = asymp.LCL, ymax = asymp.UCL),shape = 2)

```

```{r}
library(ggeffects)

data_in_shape <- data_in_shape %>%
  mutate(logRT = log10(`Reaction Time`),
         PID = as.factor(PID),
         SOA = as.factor(SOA),
         condition = as.factor(condition),
         Session = as.factor(Session))
m <- lmer(logRT ~ Session *SOA * condition + (1 | `PID`), data_in_shape )

pred <- ggpredict(m)

# m <- aov_ez(id = 'PID', dv = "RT", between = NULL, within = c('Session', 'SOA', 'condition'), data = data_in_shape )
# m1 <- aov_4(log10(`Reaction Time`) ~ 1 + (Session *SOA * condition | `PID`), data = data_in_shape )

em <- emmeans(m,~ Session + SOA + condition)
plot(pred)

pred <- ggpredict(m, ~ SOA + condition)
ggplot(data = pred, aes(x, y=predicted, ymin = conf.low, ymax = conf.high, group = group, col = group)) +
  geom_pointrange()


```

