---
title: "Extracting data for Task Count Down"
params:
  experimentID: [15096,16303]
  rootdir: /home/maximilien.chaumon/owncloud/Lab/00-Projects/TimeSocialDistancing/DATA
output:
  html_document:
    df_print: paged
    toc: yes
  html_notebook:
    code_folding: hide
    toc: yes
---


```{r, message=F}
library(tidyverse)
library(ggbeeswarm)
source('helpers.R')
```

```{r, message=F}

datadir = file.path(params$rootdir,paste0('data_exp_', paste(params$experimentID,collapse='-'), '_', ExperimentName[1]))
outdir = paste(datadir,'processed',sep='_')
dir.create(outdir,showWarnings = F)

experimentID <- params$experimentID

datafiles <- list.files(datadir,'S1_CountDown_r.*.csv',full.names = T)

tmpdir <- file.path(params$rootdir,'.tmp')
unlink(tmpdir,recursive=T)

if (is_empty(datafiles)){
  print('No CountDown data')
  knitr::knit_exit()
  }


```

### Read and describe data

```{r, warning=F}

orig <- T_read(datafiles) %>%
  mutate(Run = as.factor(str_replace(File,'S._CountDown_r(.).csv','\\1')))

N <- T_Nsuj(orig)


```

Number of participants who completed this task:
`r N`

```{r}

T_Complete(orig)

```

### Extracting data

```{r}

data_in_shape <- orig %>%
  filter(`Zone Name` %in% c('Zone2', 'Zone4')) %>%
  select(`Participant Private ID`,`Local Date`,Run, timelimit, number, numstep, Response,`Zone Name`) %>%
  pivot_wider(names_from = `Zone Name`,values_from = Response) %>%
  rename(FinalNumber = Zone2, EstimatedDuration = Zone4) %>%
  mutate(timelimit = as.numeric(timelimit),
         number = as.numeric(number),
         numstep = as.numeric(numstep),
         FinalNumber = as.numeric(FinalNumber)
         ) %>%
    write_csv(file.path(outdir,'S1_CountDown.csv'))
```


```{r}
data_in_shape %>%
  group_by(`Participant Private ID`) %>%
  summarize(pCorrect = mean(Correct)) %>%
ggplot(aes(x=`Participant Private ID`,y=pCorrect,col=`Participant Private ID`,group=`Participant Private ID`)) +
  geom_point(show.legend = F) +
  geom_line(show.legend = F)
```