---
title: "Extracting data for Task Temporal Landmark"
params:
  experimentID: [15096,16303]
output:
  html_document:
    df_print: paged
    toc: yes
  html_notebook:
    code_folding: hide
    toc: yes
---
<!-- # This is the Blursday database paper source code. -->
<!-- # This code was used to prepare the following article: -->
<!-- # XXX Ref. to add XXX -->
<!-- # -->
<!-- # The live application of the server can be accessed at  -->
<!-- # https://dnacombo.shinyapps.io/Blursday/ -->
<!-- # This code is publicly available at -->
<!-- # https://github.com/dnacombo/TSDshiny -->

<!-- #     Copyright (C) 2021  Maximilien Chaumon -->
<!-- # -->
<!-- #     This program is free software: you can redistribute it and/or modify -->
<!-- #     it under the terms of the GNU General Public License as published by -->
<!-- #     the Free Software Foundation, either version 3 of the License, or -->
<!-- #     (at your option) any later version. -->
<!-- # -->
<!-- #     This program is distributed in the hope that it will be useful, -->
<!-- #     but WITHOUT ANY WARRANTY; without even the implied warranty of -->
<!-- #     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the -->
<!-- #     GNU General Public License for more details. -->
<!-- # -->
<!-- #     You should have received a copy of the GNU General Public License -->
<!-- #     along with this program.  If not, see <http://www.gnu.org/licenses/>. -->


```{r, message=F}
library(tidyverse)
library(ggbeeswarm)
source('helpers.R')
```

```{r, message=F}

datadir = file.path(dirData,paste0('data_exp_', paste(params$experimentID,collapse='-'), '_', ExperimentName[1]))
outdir = paste(datadir,'processed',sep='_')
dir.create(outdir,showWarnings = F)

experimentID <- params$experimentID

datafiles <- list.files(datadir,'S1_TemporalLandmark_r.*.csv',full.names = T)

tmpdir <- file.path(dirData,'.tmp')
unlink(tmpdir,recursive=T)

if (is_empty(datafiles)){
  print('No Implicit data')
  knitr::knit_exit()
  }

```

### Read and describe data

```{r, warning=F}

orig <- T_read(datafiles) %>%
  mutate(Run = as.factor(str_replace(File,'S._TemporalLandmark_r(.).csv','\\1')),
         `Reaction Time` = as.numeric(`Reaction Time`))

N <- T_Nsuj(orig)


```

Number of participants who completed this task:
`r N`

```{r}

T_Complete(orig)

```

### Extracting data

```{r}

(data_in_shape <- orig %>%
  filter(`Screen Name` == 'day',`Zone Type` == 'response_text_entry') %>%
  mutate(`Local Date` = parse_datetime(`Local Date`,format = '%d/%m/%Y %H:%M:%S'),
         Response = as.factor(str_to_lower(str_match(Response,'monday|tuesday|wednesday|thursday|friday|saturday|sunday'))),
         DoW = lubridate::wday(`Local Date`,label=T,locale='en_US.UTF-8') )%>%
  select(`Participant Private ID`,`Local Date`,
         `Reaction Time`,`Response`,DoW,`Task Version`, `Experiment ID`)) %>%
  write_csv(file.path(outdir,'S1_TemporalLandmark.csv'))
```


```{r}
ggplot(data_in_shape,aes(x=Response,y=`Reaction Time`,col=`Participant Private ID`)) +
  geom_jitter(show.legend = F) +
  theme(axis.text.x = element_text(angle=30,hjust = 1))
```



