---
title: "Extracting data for Task Delay Discouting"
params:
  ExperimentID: [15096,16303]
output:
  html_document:
    df_print: paged
    toc: yes
  html_notebook:
    code_folding: hide
    toc: yes
---

<!-- # This is the Blursday database paper source code. -->
<!-- # This code was used to prepare the following article: -->
<!-- # XXX Ref. to add XXX -->
<!-- # -->
<!-- # The live application of the server can be accessed at  -->
<!-- # https://dnacombo.shinyapps.io/Blursday/ -->
<!-- # This code is publicly available at -->
<!-- # https://github.com/dnacombo/TSDshiny -->

<!-- #     Copyright (C) 2021  Maximilien Chaumon -->
<!-- # -->
<!-- #     This program is free software: you can redistribute it and/or modify -->
<!-- #     it under the terms of the GNU General Public License as published by -->
<!-- #     the Free Software Foundation, either version 3 of the License, or -->
<!-- #     (at your option) any later version. -->
<!-- # -->
<!-- #     This program is distributed in the hope that it will be useful, -->
<!-- #     but WITHOUT ANY WARRANTY; without even the implied warranty of -->
<!-- #     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the -->
<!-- #     GNU General Public License for more details. -->
<!-- # -->
<!-- #     You should have received a copy of the GNU General Public License -->
<!-- #     along with this program.  If not, see <http://www.gnu.org/licenses/>. -->

```{r, message=F}
library(tidyverse)
library(ggbeeswarm)
source('helpers.R')
```

```{r, message=F}

datadir = file.path(dirData,paste0('data_exp_', paste(params$experimentID,collapse='-'), '_', ExperimentName[1]))
outdir = paste(datadir,'processed',sep='_')
dir.create(outdir,showWarnings = F)

experimentID <- params$experimentID

datafiles <- list.files(datadir,'S1_1back_r.*.csv',full.names = T)

tmpdir <- file.path(dirData,'.tmp')
unlink(tmpdir,recursive=T)

if (is_empty(datafiles)){
  print('No 1back data')
  knitr::knit_exit()
  }


```

### Read and describe data

```{r, warning=F}

orig <- T_read(datafiles) %>%
  mutate(Run = as.factor(str_replace(File,'S._1back_r(.).csv','\\1')))

N <- T_Nsuj(orig)


```

Number of participants who completed this task:
`r N`

```{r}

T_Complete(orig)

```

### Extracting data

```{r}

data_in_shape <- orig %>%
  filter(display == 'block1back',Attempt == 1) %>%
  select(Correct,ILI,`Reaction Time`,`Participant Private ID`,`Local Date`,Run) %>%
  mutate(Correct = as.logical(plyr::mapvalues(Correct,from=c('1','0'),to=c(T,F))),
         ILI = as.numeric(ILI),
         `Reaction Time` = as.numeric(`Reaction Time`)) %>%
    write_csv(file.path(outdir,'S1_1back.csv'))
```


```{r}
data_in_shape %>%
  group_by(`Participant Private ID`) %>%
  summarize(pCorrect = mean(Correct)) %>%
ggplot(aes(x=`Participant Private ID`,y=pCorrect,col=`Participant Private ID`,group=`Participant Private ID`)) +
  geom_point(show.legend = F) +
  geom_line(show.legend = F)
```